-- LOST
DROP TABLE LOST;
DROP SEQUENCE LOST_SEQ;

DROP TABLE FIND;
DROP SEQUENCE FIND_SEQ;

DROP TABLE QNA;
DROP SEQUENCE QNA_SEQ;

DROP TABLE LAF_MEMBER;
DROP TABLE POWER_CODE;
DROP TABLE STATUS_CODE;
DROP TABLE NOTICE;
DROP SEQUENCE NOTICE_SEQ;

-- 코드
CREATE TABLE POWER_CODE(
    PCCODE      VARCHAR2(10)    PRIMARY KEY,
    CODENAME    VARCHAR2(20)    NOT NULL
);

INSERT INTO POWER_CODE VALUES ('LAF000', '관리자');
INSERT INTO POWER_CODE VALUES ('LAF001', '사용자');

-- 계정상태
CREATE TABLE STATUS_CODE(
    SCCODE      NUMBER(2)         PRIMARY KEY,
    STATUSNAME    VARCHAR2(20)      NOT NULL
);
INSERT INTO STATUS_CODE VALUES (0, '사용중단');
INSERT INTO STATUS_CODE VALUES (1, '사용중');

-- 회원/관리자 
CREATE TABLE LAF_MEMBER(
    MID         VARCHAR2(30)    PRIMARY KEY,
    MPW         VARCHAR2(30)    NOT NULL,
    MNAME       VARCHAR2(30)    NOT NULL,
    MEMAIL      VARCHAR2(30)    NOT NULL,
    MADDRESS    VARCHAR2(200)   NOT NULL,
    MTEL        VARCHAR2(13)    NOT NULL,
    MBIRTH      DATE            NOT NULL,
    MQUIZ       VARCHAR2(100)   NOT NULL,
    MANSWER     VARCHAR2(50)    NOT NULL,
    MRDATE      DATE            DEFAULT SYSDATE,
    PCCODE      VARCHAR2(10)    DEFAULT 'LAF001' REFERENCES POWER_CODE (PCCODE),
    SCCODE      NUMBER(2)       DEFAULT 1        REFERENCES STATUS_CODE (SCCODE)
);


-- 분실물 게시판
CREATE TABLE LOST(
    LNO         VARCHAR2(20)      PRIMARY KEY,
    LTITLE      VARCHAR2(90)    NOT NULL,
    LCONTENT    VARCHAR2(3000)  NOT NULL,
    MID         VARCHAR2(30)    REFERENCES LAF_MEMBER (MID),
    LRDATE      DATE            DEFAULT SYSDATE,
    LOB         VARCHAR2(30)    NOT NULL,
    LLOCAL      VARCHAR2(100)   NOT NULL,
    LLOCATION   VARCHAR2(100)   NOT NULL,
    LDATE       DATE            NOT NULL,
    LPHOTO      VARCHAR2(30),
    LHIT        NUMBER(6)       DEFAULT 0,
    LTEL        VARCHAR2(13)    NOT NULL,
    LIP         VARCHAR2(20)    NOT NULL
);

CREATE SEQUENCE LOST_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

-- 습득물 게시판
CREATE TABLE FIND(
    FNO         VARCHAR2(20)       PRIMARY KEY,
    FTITLE      VARCHAR2(90)    NOT NULL,
    FCONTENT    VARCHAR2(3000)  NOT NULL,
    MID         VARCHAR2(30)    REFERENCES LAF_MEMBER (MID),
    FRDATE      DATE            DEFAULT SYSDATE,
    FOB         VARCHAR2(30)    NOT NULL,
    FSTATUS     VARCHAR2(30)    DEFAULT '보관중',
    FLOCAL      VARCHAR2(100)   NOT NULL,
    FLOCATION   VARCHAR2(100)   NOT NULL,
    FDATE       DATE            NOT NULL,
    FSTORAGE    VARCHAR2(100)   NOT NULL,
    FPHOTO      VARCHAR2(30),
    FHIT        NUMBER(6)       DEFAULT 0,
    FTEL        VARCHAR2(13)    NOT NULL,
    FIP         VARCHAR2(20)    NOT NULL
);

CREATE SEQUENCE FIND_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

-- QNA
CREATE TABLE QNA(
    QNO         NUMBER(6)       PRIMARY KEY,
    QTITLE      VARCHAR2(90)    NOT NULL,
    QCONTENT    VARCHAR2(3000)  NOT NULL,
    MID         VARCHAR2(30)    REFERENCES LAF_MEMBER (MID),
    QDATE       DATE            DEFAULT SYSDATE,
    QFILENAME   VARCHAR2(30),
    QHIT        NUMBER(6)       DEFAULT 0,
    QGROUP      NUMBER(6)       NOT NULL,
    QSTEP       NUMBER(6)       NOT NULL,
    QINDENT     NUMBER(6)       NOT NULL,
    QIP         VARCHAR2(20)    NOT NULL
);

CREATE SEQUENCE QNA_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
    
-- 공지사항 게시판
CREATE TABLE NOTICE(
    NNO         NUMBER(6)       PRIMARY KEY,
    NTITLE      VARCHAR2(90)    NOT NULL,
    NCONTENT    VARCHAR2(3000)  NOT NULL,
    NFILENAME   VARCHAR2(30),
    NHIT        NUMBER(6)       DEFAULT 0,
    NDATE       DATE            DEFAULT SYSDATE
);

CREATE SEQUENCE NOTICE_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

COMMIT;